try {
    console.log("Try Catch Starts Here")
} catch (error) {
    
}