try {
    console.log("Try Catch Starts Here");
    console.log(X);
    console.log("error solved");
} catch (error) {
    console.log("Catch Block ");
    console.log("Your eroor is:", error);
}